In [2]:
import numpy as np
# generate random data - 2 rows, 3 columns
data = np.random.randn(2,3)
data

array([[-0.20254002, -0.89249626, -2.09202678],
       [-0.81039354, -1.00506661,  0.00803546]])

In [3]:
# multiply data * 10
data * 10

array([[ -2.02540021,  -8.92496257, -20.92026779],
       [ -8.10393538, -10.05066614,   0.08035463]])

In [4]:
# add the data to itself
data + data

array([[-0.40508004, -1.78499251, -4.18405356],
       [-1.62078708, -2.01013323,  0.01607093]])

In [5]:
# find shape of array
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [10]:
# create a numpy array from defined values
data1 = [6, 7.5, 8,0 ,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
# second 2D array
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# count the number of dimension
arr2.ndim

2

In [13]:
# 2 rows, 2 columns
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
# create array with 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# array of zero 3 rows and 6 columns
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
# 2 arrays, 3 rows, 2 columns
# empty creates an array without initializing values
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
# array with 0 to 15 numbers
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
# build integer array 
arr= np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [26]:
# reassign the data type
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [29]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])